title: "Frutas de diseño"
author: "El vivero"
description: ""
url: "https://elvivero.es"
baseurl: "/frutas"
lang: "es"

sass:
  style: expanded
  sourcemap: development

thumbor:
  url: "https://img.haztecaso.com"
  key: "KFV^znjSZjp&Fo&D552!T8U#44Rfvdow"
  sizes:
    - 100
    - 200
    - 300
    - 400
    - 800
    - 1200
    - 1800
    - 2048

plugins: 
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-image-size

permalink: /:title/
exclude: 
  - README.md
  - Gemfile
  - Gemfile.lock
  - default.nix
  - gemset.nix
  - readme.md
  - Makefile
  - result
  - flake.*
