title: Frutas de diseño
author: El vivero
description: >
  Frutas de diseño presenta una selección de marcas de frutas, con foco en los
  diseños creados en España desde finales de los años 50 del siglo XX. Unos
  diseños populares que llevan años a nuestro alrededor y que se han ido
  actualizando casi inadvertidamente.
url: "https://elvivero.es"
baseurl: "/frutas"
lang: "es"

sass:
  style: expanded
  sourcemap: development

thumbor:
  url: "https://img.haztecaso.com"
  key: "KFV^znjSZjp&Fo&D552!T8U#44Rfvdow"
  sizes:
    - 200
    - 300
    - 440
    - 600
    - 728
    - 984 
    - 1240
    - 1380
    - 1560
    - 1800
    - 2048

plugins: 
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-image-size

jekyll-minifier:
  uglifier_args:
    harmony: true

permalink: /:title/
exclude: 
  - README.md
  - Gemfile
  - Gemfile.lock
  - default.nix
  - gemset.nix
  - readme.md
  - Makefile
  - result
  - flake.*
